apiVersion: apps/v1
kind: Deployment
metadata:
  name: app
spec:
  replicas: 4
  template:
    spec:
      containers:
        - name: app
          resources:
            requests:
              cpu: 250m
              memory: 256Mi
            limits:
              cpu: 1000m
              memory: 1024Mi
          env:
            - name: ASPNETCORE_ENVIRONMENT
              value: "Production"
