apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: app
  labels:
    app.kubernetes.io/name: app
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: app
  policyTypes:
    - Ingress
    - Egress
  ingress:
    - from:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: ingress-nginx
        - podSelector:
            matchLabels:
              app.kubernetes.io/name: app
      ports:
        - port: 8080
          protocol: TCP
  egress:
    - to: []
      ports:
        - port: 53
          protocol: UDP
        - port: 53
          protocol: TCP
        - port: 443
          protocol: TCP
        - port: 4317
          protocol: TCP
        - port: 5432
          protocol: TCP
        - port: 6379
          protocol: TCP
