apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-rbac-cm
  namespace: argocd
  labels:
    app.kubernetes.io/part-of: argocd
data:
  policy.default: role:readonly
  policy.csv: |
    # Grant platform engineers full administrative rights
    g, platform-engineering-team, role:admin
    
    # Developers get sync rights for dev/qa
    p, role:developer, applications, get, *, allow
    p, role:developer, applications, sync, dev/*, allow
    p, role:developer, applications, sync, qa/*, allow
    g, developers, role:developer
    
    # Release Managers get full management of apps in all envs
    p, role:release-manager, applications, *, *, allow
    g, release-managers, role:release-manager
